[features]
seeds = false
skip-lint = false
[programs.localnet]
token_vesting = "GHUcyYWLFtz3wPc4KXswCvpS2ihVx9i4BAcAJyMmHMDJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/nobrain/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
